name: Build and Push Docker Image
docker run -d \
  --name node-hy2 \
  -p 3000:3000/udp \
  -p 3000:3000/tcp \
  -e ARGO_TOKEN="eyJhIjoiM2NlMmVhYzdiZmRjNjk3YTc1NDI0YjNjZjNhMWU3ZTAiLCJ0IjoiZjhkYmVmODAtODQ4OS00NTczLTg3NWYtZTJlYzBmOGExOGQzIiwicyI6Ik1UUTVOREJoTjJVdE5XRTNOeTAwT0dRd0xXRXdZemN0TUdVNVl6UmtPR1E0WmpBMiJ9" \
  -e ARGO_DOMAIN="kr.wasmrsbcf.kdns.fr" \
  -e UDP_TYPE="hy2" \
  ghcr.io/nodejsvml-hy2:latest
